/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Panel: typeof import('primevue/panel')['default']
  }
}
